steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - sample_http
  - --region=us-central1
  - --source=.
  - --trigger-http
  - --runtime=python37
  - --allow-unauthenticated